spring:
  application:
    name: property-app

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

jwt:
  expiration: 900000        # 15 minutes
  refresh-expiration: 604800000  # 7 days

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG

server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always

aws:
  region: ap-southeast-1
  s3:
    bucket: ys-property-images